# Generated by Django 5.1.6 on 2025-02-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_sale_product_sales_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sales_price',
            new_name='sale_price',
        ),
    ]
