# Generated by Django 5.1.6 on 2025-02-20 08:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.TextField(blank=True, null=True)),
                ('productCategory', models.CharField(choices=[('ELEC', 'Electronics & Gadgets'), ('FASH', 'Fashion & Apparel'), ('HOME', 'Home & Living'), ('BEAU', 'Beauty & Personal Care'), ('HEAL', 'Health & Wellness'), ('BOOK', 'Books & Stationery'), ('TOYS', 'Toys'), ('KIDS', 'Kids & Baby Products'), ('SPOR', 'Sports & Outdoors'), ('GROC', 'Groceries & Food Items'), ('AUTO', 'Automotive & Tools'), ('PET', 'Pet Supplies')], default='ELEC', max_length=10)),
                ('Rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('Images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='product_images/'), blank=True, null=True, size=None)),
            ],
        ),
    ]
